[server]
host: 0.0.0.0
port: 7125
socket_path: /home/ajs/printer_data/comms/moonraker.sock
klippy_uds_address: /home/ajs/printer_data/comms/klippy.sock


[authorization]
trusted_clients:
    127.0.0.1
    ::1
    192.168.0.0/16
    10.0.0.0/8

[update_manager mainsail]
path: /home/ajs/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/ajs/mainsail-config
primary_branch: master
type: git_repo
