[server]
host: 0.0.0.0
port: 7125
klippy_uds_path: /home/ajs/printer_data/comms/klippy.sock
unix_socket_path: /home/ajs/printer_data/comms/moonraker.sock

[authorization]
trusted_clients:
    127.0.0.1
    ::1
    192.168.0.0/16
    10.0.0.0/8

[update_manager mainsail]
path: /home/ajs/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json
